using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AGenius.UsefulStuff.Helpers
{
    /// <summary>Provides a way to get the Mime type from a file extension</summary>
    public static class MimeTypesList
    {
        private static readonly Lazy<IDictionary<string, string>> _mappings = new Lazy<IDictionary<string, string>>(BuildList);

        #region Mime List
        private readonly static Dictionary<string, string> base_mime_mappings_list = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
               
                {".323", "text/h323"},
                {".3dm", "x-world/x-3dmf" },
                {".3dmf", "x-world/x-3dmf" },
                {".3g2", "video/3gpp2"},
                {".3gp", "video/3gpp"},
                {".3gp2", "video/3gpp2"},
                {".3gpp", "video/3gpp"},
                {".7z", "application/x-7z-compressed"},

                {".a", "application/octet-stream" },
                {".aa", "audio/audible"},
                {".aab", "application/x-authorware-bin" },
                {".aac", "audio/aac"},
                {".aaf", "application/octet-stream"},
                {".aam", "application/x-authorware-map" },
                {".aas", "application/x-authorware-seg" },
                {".aax", "audio/vnd.audible.aax"},
                {".abc", "text/vnd.abc" },
                {".ac3", "audio/ac3"},
                {".aca", "application/octet-stream"},
                {".accda", "application/msaccess.addin"},
                {".accdb", "application/msaccess"},
                {".accdc", "application/msaccess.cab"},
                {".accde", "application/msaccess"},
                {".accdr", "application/msaccess.runtime"},
                {".accdt", "application/msaccess"},
                {".accdw", "application/msaccess.webapplication"},
                {".accft", "application/msaccess.ftemplate"},
                {".acgi", "text/html" },
                {".acx", "application/internet-property-stream"},
                {".addin", "text/xml"},
                {".ade", "application/msaccess"},
                {".adobebridge", "application/x-bridge-url"},
                {".adp", "application/msaccess"},
                {".adt", "audio/vnd.dlna.adts"},
                {".adts", "audio/aac"},
                {".afl", "video/animaflex"},
                {".afm", "application/octet-stream"},
                {".ai", "application/postscript"},                
                {".aif", "audio/aiff"},
                {".aifc", "audio/aiff"},                
                {".aiff", "audio/aiff"},
                {".aim", "application/x-aim"},
                {".aip", "text/x-audiosoft-intra"},
                {".air", "application/vnd.adobe.air-application-installer-package+zip"},
                {".amc", "application/mpeg"},
                {".ani", "application/x-navi-animation"},
                {".anx", "application/annodex"},
                {".aos", "application/x-nokia-9000-communicator-add-on-software"},
                {".apk", "application/vnd.android.package-archive"},
                {".apng", "image/apng"},
                {".application", "application/x-ms-application"},
                {".aps", "application/mime"},
                {".arc", "application/octet-stream"},
                {".arj", "application/arj"},
                {".art", "image/x-jg"},               
                {".asa", "application/xml"},
                {".asax", "application/xml"},
                {".ascx", "application/xml"},
                {".asd", "application/octet-stream"},
                {".asf", "video/x-ms-asf"},               
                {".ashx", "application/xml"},
                {".asi", "application/octet-stream"},                
                {".asm", "text/x-asm"},
                {".asmx", "application/xml"},
                {".asp", "text/asp"},
                {".aspx", "application/xml"},
                {".asr", "video/x-ms-asf"},               
                {".asx", "video/x-ms-asf"},
                {".atom", "application/atom+xml"},               
                {".au", "audio/basic"},
                {".avci", "image/avci"},
                {".avcs", "image/avcs"},
                {".avi", "video/x-msvideo"},
                {".avif", "image/avif"},
                {".avifs", "image/avif-sequence"},
                {".avs", "video/avs-video"},
                {".axa", "audio/annodex"},
                {".axs", "application/olescript"},
                {".axv", "video/annodex"},

                {".bas", "text/plain"},
                {".bcpio", "application/x-bcpio"},
                {".bin", "application/octet-stream"},
                {".bm", "image/bmp"},
                {".bmp", "image/bmp"},
                {".boo", "application/book"},
                {".book", "application/book"},
                {".boz", "application/x-bzip2"},
                {".bsh", "application/x-bsh"},
                {".bz", "application/x-bzip"},
                {".bz2", "application/x-bzip2"},

                {".c", "text/plain"},
                {".c++", "text/plain"},
                {".cab", "application/octet-stream"},
                {".caf", "audio/x-caf"},
                {".calx", "application/vnd.ms-office.calx"},
                {".cat", "application/vnd.ms-pki.seccat"},
                {".cc", "text/plain"},
                {".ccad", "application/clariscad"},
                {".cco", "application/x-cocoa"},
                {".cd", "text/plain"},
                {".cdda", "audio/aiff"},
                {".cdf", "application/x-cdf"},
                {".cer", "application/x-x509-ca-cert"},
                {".cfg", "text/plain"},
                {".cha", "application/x-chat"},
                {".chat", "application/x-chat"},
                {".chm", "application/octet-stream"},
                {".class", "application/x-java-applet"},
                {".clp", "application/x-msclip"},
                {".cmd", "text/plain"},
                {".cmx", "image/x-cmx"},
                {".cnf", "text/plain"},
                {".cod", "image/cis-cod"},
                {".com", "application/octet-stream"},
                {".conf", "text/plain"},
                {".config", "application/xml"},
                {".contact", "text/x-ms-contact"},
                {".coverage", "application/xml"},
                {".cpio", "application/x-cpio"},
                {".cpp", "text/plain"},
                {".cpt", "application/x-cpt"},
                {".crd", "application/x-mscardfile"},
                {".crl", "application/pkix-crl"},
                {".crt", "application/x-x509-ca-cert"},
                {".cs", "text/plain"},
                {".csdproj", "text/plain"},
                {".csh", "application/x-csh"},
                {".csproj", "text/plain"},
                {".css", "text/css"},
                {".csv", "text/csv"},
                {".cur", "application/octet-stream"},
                {".cxx", "text/plain"},
                {".czx", "application/x-czx"},

                {".dat", "application/octet-stream"},
                {".datasource", "application/xml"},
                {".dbproj", "text/plain"},
                {".dcr", "application/x-director"},
                {".deepv", "application/x-deepv"},
                {".def", "text/plain"},
                {".deploy", "application/octet-stream"},
                {".der", "application/x-x509-ca-cert"},
                {".dgml", "application/xml"},
                {".dib", "image/bmp"},
                {".dif", "video/x-dv"},
                {".dir", "application/x-director"},
                {".disco", "text/xml"},
                {".divx", "video/divx"},
                {".dl", "video/dl"},
                {".dll", "application/x-msdownload"},
                {".dll.config", "text/xml"},
                {".dlm", "text/dlm"},
                {".doc", "application/msword"},
                {".docm", "application/vnd.ms-word.document.macroEnabled.12"},
                {".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
                {".dot", "application/msword"},
                {".dotm", "application/vnd.ms-word.template.macroEnabled.12"},
                {".dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
                {".dp", "application/commonground"},
                {".drw", "application/drafting"},
                {".dsp", "application/octet-stream"},
                {".dsw", "text/plain"},
                {".dtd", "text/xml"},
                {".dtsConfig", "text/xml"},
                {".dump", "application/octet-stream"},
                {".dv", "video/x-dv"},
                {".dvi", "application/x-dvi"},
                {".dwf", "model/vnd.dwf"},
                {".dwg", "image/vnd.dwg"},
                {".dwp", "application/octet-stream"},
                {".dxf", "image/vnd.dwg"},
                {".dxr", "application/x-director"},

                {".el", "text/x-script.elisp"},
                {".elc", "application/x-elc"},
                {".emf", "image/emf"},
                {".eml", "message/rfc822"},
                {".emz", "application/octet-stream"},
                {".env", "application/x-envoy"},
                {".eot", "application/vnd.ms-fontobject"},
                {".eps", "application/postscript"},
                {".es", "application/ecmascript"},               
                {".etl", "application/etl"},
                {".etx", "text/x-setext"},
                {".evy", "application/envoy"},
                {".exe", "application/octet-stream"},
                {".exe.config", "text/xml"},

                {".f", "text/plain"},
                {".f4v", "video/mp4"},
                {".f77", "text/x-fortran"},
                {".f90", "text/plain"},
                {".fdf", "application/vnd.fdf"},
                {".fif", "image/fif"},
                {".filters", "application/xml"},
                {".fla", "application/octet-stream"},
                {".flac", "audio/flac"},
                {".fli", "video/fli"},
                {".flo", "image/florian"},
                {".flr", "x-world/x-vrml"},
                {".flv", "video/x-flv"},
                {".flx", "text/vnd.fmi.flexstor"},
                {".fmf", "video/x-atomic3d-feature"},
                {".for", "text/x-fortran"},
                {".fpx", "image/vnd.fpx"},
                {".frl", "application/freeloader"},
                {".fsscript", "application/fsharp-script"},
                {".fsx", "application/fsharp-script"},
                {".funk", "audio/make"},

                {".g", "text/plain"},
                {".g3", "image/g3fax"},
                {".generictest", "application/xml"},
                {".gif", "image/gif"},
                {".gl", "video/gl"},
                {".gpx", "application/gpx+xml"},
                {".group", "text/x-ms-group"},
                {".gsd", "audio/x-gsm"},
                {".gsm", "audio/x-gsm"},
                {".gsp", "application/x-gsp"},
                {".gss", "application/x-gss"},
                {".gtar", "application/x-gtar"},
                {".gz", "application/x-gzip"},
                {".gzip", "application/x-gzip"},

                {".h", "text/plain"},
                {".hdf", "application/x-hdf"},
                {".hdml", "text/x-hdml"},
                {".heic", "image/heic"},
                {".heics", "image/heic-sequence"},
                {".heif", "image/heif"},
                {".heifs", "image/heif-sequence"},
                {".help", "application/x-helpfile"},
                {".hgl", "application/vnd.hp-hpgl"},
                {".hh", "text/plain"},
                {".hhc", "application/x-oleobject"},
                {".hhk", "application/octet-stream"},
                {".hhp", "application/octet-stream"},
                {".hlb", "text/x-script"},
                {".hlp", "application/winhlp"},
                {".hpg", "application/vnd.hp-hpgl"},
                {".hpgl", "application/vnd.hp-hpgl"},
                {".hpp", "text/plain"},
                {".hqx", "application/binhex"},
                {".hta", "application/hta"},
                {".htc", "text/x-component"},
                {".htm", "text/html"},
                {".html", "text/html"},
                {".htmls", "text/html"},
                {".htt", "text/webviewhtml"},
                {".htx", "text/html"},
                {".hxa", "application/xml"},
                {".hxc", "application/xml"},
                {".hxd", "application/octet-stream"},
                {".hxe", "application/xml"},
                {".hxf", "application/xml"},
                {".hxh", "application/octet-stream"},
                {".hxi", "application/octet-stream"},
                {".hxk", "application/xml"},
                {".hxq", "application/octet-stream"},
                {".hxr", "application/octet-stream"},
                {".hxs", "application/octet-stream"},
                {".hxt", "text/html"},
                {".hxv", "application/xml"},
                {".hxw", "application/octet-stream"},
                {".hxx", "text/plain"},

                {".i", "text/plain"},
                {".ical", "text/calendar"},
                {".icalendar", "text/calendar"},
                {".ice", "x-conference/x-cooltalk"},
                {".ico", "image/x-icon"},
                {".ics", "text/calendar"},
                {".idc", "text/plain"},
                {".idl", "text/plain"},
                {".ief", "image/ief"},
                {".iefs", "image/ief"},
                {".ifb", "text/calendar"},
                {".iges", "application/iges"},
                {".igs", "application/iges"},
                {".iii", "application/x-iphone"},
                {".ima", "application/x-ima"},
                {".imap", "application/x-httpd-imap"},
                {".inc", "text/plain"},
                {".inf", "application/inf"},
                {".ini", "text/plain"},
                {".ins", "application/x-internet-signup"},
                {".ip", "application/x-ip2"},
                {".ipa", "application/x-itunes-ipa"},
                {".ipg", "application/x-itunes-ipg"},
                {".ipproj", "text/plain"},
                {".ipsw", "application/x-itunes-ipsw"},
                {".iqy", "text/x-ms-iqy"},
                {".isma", "application/octet-stream"},
                {".ismv", "application/octet-stream"},
                {".isp", "application/x-internet-signup"},
                {".isu", "video/x-isvideo"},
                {".it", "audio/it"},
                {".ite", "application/x-itunes-ite"},
                {".itlp", "application/x-itunes-itlp"},
                {".itms", "application/x-itunes-itms"},
                {".itpc", "application/x-itunes-itpc"},
                {".iv", "application/x-inventor"},
                {".ivf", "video/x-ivf"},
                {".ivr", "i-world/i-vrml"},
                {".ivy", "application/x-livescreen"},

                {".jam", "audio/x-jam"},
                {".jar", "application/java-archive"},
                {".jav", "text/plain"},
                {".java", "text/plain"},
                {".jck", "application/liquidmotion"},
                {".jcm", "application/x-java-commerce"},
                {".jcz", "application/liquidmotion"},
                {".jfif", "image/jpeg"},
                {".jfif-tbnl", "image/jpeg"},
                {".jnlp", "application/x-java-jnlp-file"},
                {".jpb", "application/octet-stream"},
                {".jpe", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".jpg", "image/jpeg"},
                {".jps", "image/x-jps"},
                {".js", "application/javascript"},
                {".json", "application/json"},
                {".jsx", "text/jscript"},
                {".jsxbin", "text/plain"},
                {".jut", "image/jutvision"},

                {".kar", "audio/midi"},
                {".ksh", "application/x-ksh"},

                {".la", "audio/nspaudio"},
                {".lam", "audio/x-liveaudio"},
                {".latex", "application/x-latex"},
                {".lha", "application/octet-stream"},
                {".lhx", "application/octet-stream"},
                {".library-ms", "application/windows-library+xml"},
                {".list", "text/plain"},
                {".lit", "application/x-ms-reader"},
                {".lma", "audio/nspaudio"},
                {".loadtest", "application/xml"},
                {".log", "text/plain"},
                {".lpk", "application/octet-stream"},
                {".lsf", "video/x-la-asf"},
                {".lsp", "application/x-lisp"},
                {".lst", "text/plain"},
                {".lsx", "text/x-la-asf"},
                {".ltx", "application/x-latex"},
                {".lzh", "application/octet-stream"},
                {".lzx", "application/octet-stream"},

                {".m", "text/plain"},
                {".m13", "application/x-msmediaview"},
                {".m14", "application/x-msmediaview"},
                {".m1v", "video/mpeg"},
                {".m2a", "audio/mpeg"},
                {".m2t", "video/vnd.dlna.mpeg-tts"},
                {".m2ts", "video/vnd.dlna.mpeg-tts"},
                {".m2v", "video/mpeg"},
                {".m3u", "audio/x-mpequrl"},
                {".m3u8", "audio/x-mpegurl"},
                {".m4a", "audio/m4a"},
                {".m4b", "audio/m4b"},
                {".m4p", "audio/m4p"},
                {".m4r", "audio/x-m4r"},
                {".m4v", "video/x-m4v"},
                {".mac", "image/x-macpaint"},
                {".mak", "text/plain"},
                {".man", "application/x-troff-man"},
                {".manifest", "application/x-ms-manifest"},
                {".map", "application/x-navimap"},
                {".mar", "text/plain"},
                {".master", "application/xml"},
                {".mbd", "application/mbedlet"},
                {".mbox", "application/mbox"},
                {".mc$", "application/x-magic-cap-package-1.0"},
                {".mcd", "application/mcad"},
                {".mcf", "text/mcf"},
                {".mcp", "application/netmc"},
                {".mda", "application/msaccess"},
                {".mdb", "application/x-msaccess"},
                {".mde", "application/msaccess"},
                {".mdp", "application/octet-stream"},
                {".me", "application/x-troff-me"},
                {".mfp", "application/x-shockwave-flash"},               
                {".mht", "message/rfc822"},
                {".mhtml", "message/rfc822"},
                {".mid", "application/x-midi"},
                {".midi", "audio/midi"},
                {".mif", "application/x-mif"},
                {".mime", "message/rfc822"},
                {".mix", "application/octet-stream"},
                {".mjf", "audio/x-vnd.audioexplosion.mjuicemediafile"},
                {".mjpg", "video/x-motion-jpeg"},
                {".mk", "text/plain"},
                {".mk3d", "video/x-matroska-3d"},
                {".mka", "audio/x-matroska"},
                {".mkv", "video/x-matroska"},
                {".mm", "application/base64"},
                {".mme", "application/base64"},
                {".mmf", "application/x-smaf"},
                {".mno", "text/xml"},
                {".mny", "application/x-msmoney"},
                {".mod", "audio/mod"},
                {".moov", "video/quicktime"},
                {".mov", "video/quicktime"},
                {".movie", "video/x-sgi-movie"},
                {".mp2", "audio/mpeg"},
                {".mp2v", "video/mpeg"},
                {".mp3", "audio/mpeg"},
                {".mp4", "video/mp4"},
                {".mp4v", "video/mp4"},
                {".mpa", "audio/mpeg"},
                {".mpc", "application/x-project"},
                {".mpe", "video/mpeg"},
                {".mpeg", "video/mpeg"},
                {".mpf", "application/vnd.ms-mediapackage"},
                {".mpg", "video/mpeg"},
                {".mpga", "audio/mpeg"},
                {".mpp", "application/vnd.ms-project"},
                {".mpt", "application/vnd.ms-project"},
                {".mpv", "application/vnd.ms-project"},
                {".mpv2", "video/mpeg"},
                {".mpx", "application/vnd.ms-project"},
                {".mqv", "video/quicktime"},
                {".mrc", "application/marc"},
                {".ms", "application/x-troff-ms"},
                {".msg", "application/vnd.ms-outlook"},
                {".msi", "application/octet-stream"},
                {".mso", "application/octet-stream"},
                {".mts", "video/vnd.dlna.mpeg-tts"},
                {".mtx", "application/xml"},
                {".mv", "video/x-sgi-movie"},
                {".mvb", "application/x-msmediaview"},
                {".mvc", "application/x-miva-compiled"},
                {".mxf", "application/mxf"},
                {".mxp", "application/x-mmxp"},
                {".my", "audio/make"},
                {".mzz", "application/x-vnd.audioexplosion.mzz"},

                {".nap", "image/naplps"},
                {".naplps", "image/naplps"},
                {".nc", "application/x-netcdf"},                
                {".ncm", "application/vnd.nokia.configuration-message"},
                {".nif", "image/x-niff"},
                {".niff", "image/x-niff"},
                {".nix", "application/x-mix-transfer"},
                {".nsc", "application/x-conference"},
                {".nvd", "application/x-navidoc"},
                {".nws", "message/rfc822"},

                {".o", "application/octet-stream"},
                {".ocx", "application/octet-stream"},
                {".oda", "application/oda"},
                {".odb", "application/vnd.oasis.opendocument.database"},
                {".odc", "application/vnd.oasis.opendocument.chart"},
                {".odf", "application/vnd.oasis.opendocument.formula"},
                {".odg", "application/vnd.oasis.opendocument.graphics"},
                {".odh", "text/plain"},
                {".odi", "application/vnd.oasis.opendocument.image"},
                {".odl", "text/plain"},
                {".odm", "application/vnd.oasis.opendocument.text-master"},
                {".odp", "application/vnd.oasis.opendocument.presentation"},
                {".ods", "application/vnd.oasis.opendocument.spreadsheet"},
                {".odt", "application/vnd.oasis.opendocument.text"},
                {".oga", "audio/ogg"},
                {".ogg", "audio/ogg"},
                {".ogv", "video/ogg"},
                {".ogx", "application/ogg"},
                {".omc", "application/x-omc"},
                {".omcd", "application/x-omcdatamaker"},
                {".omcr", "application/x-omcregerator"},
                {".one", "application/onenote"},
                {".onea", "application/onenote"},
                {".onepkg", "application/onenote"},
                {".onetmp", "application/onenote"},
                {".onetoc", "application/onenote"},
                {".onetoc2", "application/onenote"},
                {".opus", "audio/ogg"},
                {".orderedtest", "application/xml"},
                {".osdx", "application/opensearchdescription+xml"},
                {".otf", "application/font-sfnt"},
                {".otg", "application/vnd.oasis.opendocument.graphics-template"},
                {".oth", "application/vnd.oasis.opendocument.text-web"},
                {".otp", "application/vnd.oasis.opendocument.presentation-template"},
                {".ots", "application/vnd.oasis.opendocument.spreadsheet-template"},
                {".ott", "application/vnd.oasis.opendocument.text-template"},
                {".oxps", "application/oxps"},
                {".oxt", "application/vnd.openofficeorg.extension"},

                {".p", "text/x-pascal"},
                {".p10", "application/pkcs10"},
                {".p12", "application/pkcs-12"},
                {".p7a", "application/x-pkcs7-signature"},
                {".p7b", "application/x-pkcs7-certificates"},
                {".p7c", "application/pkcs7-mime"},
                {".p7m", "application/pkcs7-mime"},
                {".p7r", "application/x-pkcs7-certreqresp"},
                {".p7s", "application/pkcs7-signature"},
                {".part", "application/pro_eng"},
                {".pas", "text/pascal"},
                {".pbm", "image/x-portable-bitmap"},
                {".pcast", "application/x-podcast"},
                {".pcl", "application/vnd.hp-pcl"},
                {".pct", "image/pict"},
                {".pcx", "image/x-pcx"},
                {".pcz", "application/octet-stream"},
                {".pdb", "chemical/x-pdb"},
                {".pdf", "application/pdf"},
                {".pfb", "application/octet-stream"},
                {".pfm", "application/octet-stream"},
                {".pfunk", "audio/make"},
                {".pfx", "application/x-pkcs12"},
                {".pgm", "image/x-portable-greymap"},
                {".pic", "image/pict"},
                {".pict", "image/pict"},
                {".pkg", "application/x-newton-compatible-pkg"},
                {".pkgdef", "text/plain"},
                {".pkgundef", "text/plain"},
                {".pko", "application/vnd.ms-pki.pko"},
                {".pl", "text/plain"},
                {".pls", "audio/scpls"},
                {".plx", "application/x-pixclscript"},
                {".pm", "image/x-xpixmap"},
                {".pm4", "application/x-pagemaker"},
                {".pm5", "application/x-pagemaker"},
                {".pma", "application/x-perfmon"},
                {".pmc", "application/x-perfmon"},
                {".pml", "application/x-perfmon"},
                {".pmr", "application/x-perfmon"},
                {".pmw", "application/x-perfmon"},
                {".png", "image/png"},
                {".pnm", "application/x-portable-anymap"},
                {".pnt", "image/x-macpaint"},
                {".pntg", "image/x-macpaint"},
                {".pnz", "image/png"},
                {".pot", "application/vnd.ms-powerpoint"},
                {".potm", "application/vnd.ms-powerpoint.template.macroEnabled.12"},
                {".potx", "application/vnd.openxmlformats-officedocument.presentationml.template"},
                {".pov", "model/x-pov"},
                {".ppa", "application/vnd.ms-powerpoint"},
                {".ppam", "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
                {".ppm", "image/x-portable-pixmap"},
                {".pps", "application/vnd.ms-powerpoint"},
                {".ppsm", "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
                {".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
                {".ppt", "application/vnd.ms-powerpoint"},
                {".pptm", "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
                {".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
                {".ppz", "application/vnd.ms-powerpoint"},
                {".pre", "application/x-freelance"},
                {".prf", "application/pics-rules"},
                {".prm", "application/octet-stream"},
                {".prt", "application/pro_eng"},
                {".prx", "application/octet-stream"},
                {".ps", "application/postscript"},
                {".psc1", "application/PowerShell"},
                {".psd", "application/octet-stream"},
                {".psess", "application/xml"},
                {".psm", "application/octet-stream"},
                {".psp", "application/octet-stream"},
                {".pst", "application/vnd.ms-outlook"},
                {".pub", "application/x-mspublisher"},
                {".pvu", "paleovu/x-pv"},
                {".pwz", "application/vnd.ms-powerpoint"},
                {".py", "text/x-script.phyton"},
                {".pyc", "applicaiton/x-bytecode.python"},

                {".qcp", "audio/vnd.qcelp"},
                {".qd3", "x-world/x-3dmf"},
                {".qd3d", "x-world/x-3dmf"},
                {".qht", "text/x-html-insertion"},
                {".qhtm", "text/x-html-insertion"},
                {".qif", "image/x-quicktime"},
                {".qt", "video/quicktime"},
                {".qtc", "video/x-qtc"},
                {".qti", "image/x-quicktime"},
                {".qtif", "image/x-quicktime"},
                {".qtl", "application/x-quicktimeplayer"},
                {".qxd", "application/octet-stream"},

                {".ra", "audio/x-pn-realaudio"},
                {".ram", "audio/x-pn-realaudio"},
                {".rar", "application/x-rar-compressed"},
                {".ras", "application/x-cmu-raster"},
                {".rast", "image/cmu-raster"},
                {".rat", "application/rat-file"},
                {".rc", "text/plain"},
                {".rc2", "text/plain"},
                {".rct", "text/plain"},
                {".rdlc", "application/xml"},
                {".reg", "text/plain"},
                {".resx", "application/xml"},
                {".rexx", "text/x-script.rexx"},
                {".rf", "image/vnd.rn-realflash"},
                {".rgb", "image/x-rgb"},
                {".rgs", "text/plain"},
                {".rm", "application/vnd.rn-realmedia"},
                {".rmi", "audio/mid"},
                {".rmm", "audio/x-pn-realaudio"},
                {".rmp", "audio/x-pn-realaudio"},
                {".rmvb", "application/vnd.rn-realmedia-vbr"},
                {".rng", "application/ringing-tones"},
                {".rnx", "application/vnd.rn-realplayer"},
                {".roff", "application/x-troff"},                
                {".rp", "image/vnd.rn-realpix"},
                {".rpm", "audio/x-pn-realaudio-plugin"},                
                {".rqy", "text/x-ms-rqy"},
                {".rt", "text/richtext"},                
                {".rtf", "text/richtext"},                
                {".rtx", "text/richtext"},
                {".ruleset", "application/xml"},
                {".rv", "video/vnd.rn-realvideo"},
                {".rvt", "application/octet-stream"},

                {".s", "text/x-asm"},
                {".s3m", "audio/s3m"},
                {".safariextz", "application/x-safari-safariextz"},
                {".saveme", "application/octet-stream"},
                {".sbk", "application/x-tbook"},
                {".scd", "application/x-msschedule"},
                {".scm", "application/x-lotusscreencam"},
                {".scr", "text/plain"},
                {".sct", "text/scriptlet"},
                {".sd2", "audio/x-sd2"},
                {".sdml", "text/plain"},
                {".sdp", "application/sdp"},
                {".sdr", "application/sounder"},
                {".sea", "application/sea"},
                {".searchconnector-ms", "application/windows-search-connector+xml"},
                {".set", "application/set"},
                {".setpay", "application/set-payment-initiation"},
                {".setreg", "application/set-registration-initiation"},
                {".settings", "application/xml"},
                {".sgimb", "application/x-sgimb"},
                {".sgm", "text/sgml"},
                {".sgml", "text/sgml"},
                {".sh", "application/x-sh"},
                {".shar", "application/x-shar"},
                {".shtml", "text/html"},
                {".sid", "audio/x-psid"},
                {".sit", "application/x-stuffit"},
                {".sitemap", "application/xml"},
                {".skd", "application/x-koan"},
                {".skin", "application/xml"},
                {".skm", "application/x-koan"},
                {".skp", "application/x-koan"},
                {".skt", "application/x-koan"},
                {".sl", "application/x-seelogo"},
                {".sldm", "application/vnd.ms-powerpoint.slide.macroEnabled.12"},
                {".sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide"},
                {".slk", "application/vnd.ms-excel"},
                {".sln", "text/plain"},
                {".slupkg-ms", "application/x-ms-license"},
                {".smd", "audio/x-smd"},
                {".smi", "application/smil"},
                {".smil", "application/smil"},
                {".smx", "audio/x-smd"},
                {".smz", "audio/x-smd"},
                {".snd", "audio/basic"},
                {".snippet", "application/xml"},
                {".snp", "application/octet-stream"},
                {".sol", "application/solids"},
                {".sor", "text/plain"},
                {".spc", "application/x-pkcs7-certificates"},
                {".spl", "application/futuresplash"},
                {".spr", "application/x-sprite"},
                {".sprite", "application/x-sprite"},
                {".spx", "audio/ogg"},
                {".sql", "application/sql"},
                {".src", "application/x-wais-source"},
                {".srf", "text/plain"},
                {".ssi", "text/x-server-parsed-html"},
                {".ssisdeploymentmanifest", "text/xml"},
                {".ssm", "application/streamingmedia"},
                {".sst", "application/vnd.ms-pki.certstore"},
                {".step", "application/step"},
                {".stl", "application/vnd.ms-pki.stl"},
                {".stp", "application/step"},
                {".sv4cpio", "application/x-sv4cpio"},
                {".sv4crc", "application/x-sv4crc"},
                {".svc", "application/xml"},
                {".svf", "image/vnd.dwg"},
                {".svg", "image/svg+xml"},
                {".svr", "application/x-world"},
                {".swf", "application/x-shockwave-flash"},   
                
                {".t", "application/x-troff"},
                {".talk", "text/x-speech"},
                {".tar", "application/x-tar"},
                {".tbk", "application/toolbook"},
                {".tcl", "application/x-tcl"},
                {".tcsh", "text/x-script.tcsh"},
                {".testrunconfig", "application/xml"},
                {".testsettings", "application/xml"},
                {".tex", "application/x-tex"},
                {".texi", "application/x-texinfo"},                
                {".texinfo", "application/x-texinfo"},
                {".text", "text/plain"},
                {".tgz", "application/x-compressed"},
                {".thmx", "application/vnd.ms-officetheme"},
                {".thn", "application/octet-stream"},
                {".tif", "image/tiff"},
                {".tiff", "image/tiff"},
                {".tlh", "text/plain"},
                {".tli", "text/plain"},
                {".toc", "application/octet-stream"},
                {".tr", "application/x-troff"},         
                {".trm", "application/x-msterminal"},
                {".trx", "application/xml"},
                {".ts", "video/vnd.dlna.mpeg-tts"},
                {".tsi", "audio/tsp-audio"},
                {".tsp", "application/dsptype"},
                {".tsv", "text/tab-separated-values"},
                {".ttf", "application/font-sfnt"},
                {".tts", "video/vnd.dlna.mpeg-tts"},
                {".turbot", "image/florian"},
                {".txt", "text/plain"},
                {".u32", "application/octet-stream"},
                {".uil", "text/x-uil"},
                {".uls", "text/iuls"},
                {".uni", "text/uri-list"},
                {".unis", "text/uri-list"},
                {".unv", "application/i-deas"},
                {".uri", "text/uri-list"},
                {".uris", "text/uri-list"},
                {".user", "text/plain"},
                {".ustar", "application/x-ustar"},
                {".uu", "application/octet-stream"},
                {".uue", "text/x-uuencode"},

                {".vb", "text/plain"},
                {".vbdproj", "text/plain"},
                {".vbk", "video/mpeg"},
                {".vbproj", "text/plain"},
                {".vbs", "text/vbscript"},
                {".vcd", "application/x-cdlink"},
                {".vcf", "text/x-vcard"},
                {".vcproj", "application/xml"},
                {".vcs", "text/x-vcalendar"},
                {".vcxproj", "application/xml"},
                {".vda", "application/vda"},
                {".vddproj", "text/plain"},
                {".vdo", "video/vdo"},
                {".vdp", "text/plain"},
                {".vdproj", "text/plain"},
                {".vdx", "application/vnd.ms-visio.viewer"},
                {".vew", "application/groupwise"},
                {".viv", "video/vivo"},
                {".vivo", "video/vivo"},
                {".vmd", "application/vocaltec-media-desc"},
                {".vmf", "application/vocaltec-media-file"},
                {".vml", "text/xml"},
                {".voc", "audio/voc"},
                {".vos", "video/vosaic"},
                {".vox", "audio/voxware"},
                {".vqe", "audio/x-twinvq-plugin"},
                {".vqf", "audio/x-twinvq"},
                {".vql", "audio/x-twinvq-plugin"},
                {".vrml", "application/x-vrml"},
                {".vrt", "x-world/x-vrt"},
                {".vscontent", "application/xml"},
                {".vsct", "text/xml"},
                {".vsd", "application/x-visio"},
                {".vsi", "application/ms-vsi"},
                {".vsix", "application/vsix"},
                {".vsixlangpack", "text/xml"},
                {".vsixmanifest", "text/xml"},
                {".vsmdi", "application/xml"},
                {".vspscc", "text/plain"},
                {".vss", "application/vnd.visio"},
                {".vsscc", "text/plain"},
                {".vssettings", "text/xml"},
                {".vssscc", "text/plain"},
                {".vst", "application/x-visio"},
                {".vstemplate", "text/xml"},
                {".vsto", "application/x-ms-vsto"},
                {".vsw", "application/x-visio"},
                {".vsx", "application/vnd.visio"},
                {".vtt", "text/vtt"},
                {".vtx", "application/vnd.visio"},

                {".w60", "application/wordperfect6.0"},
                {".w61", "application/wordperfect6.1"},
                {".w6w", "application/msword"},
                {".wasm", "application/wasm"},
                {".wav", "audio/wav"},
                {".wave", "audio/wav"},
                {".wax", "audio/x-ms-wax"},
                {".wb1", "application/x-qpro"},
                {".wbk", "application/msword"},
                {".wbmp", "image/vnd.wap.wbmp"},
                {".wcm", "application/vnd.ms-works"},
                {".wdb", "application/vnd.ms-works"},
                {".wdp", "image/vnd.ms-photo"},
                {".web", "application/vnd.xara"},
                {".webarchive", "application/x-safari-webarchive"},
                {".webm", "video/webm"},
                {".webp", "image/webp"}, /* https://en.wikipedia.org/wiki/WebP */
                {".webtest", "application/xml"},
                {".wiq", "application/xml"},
                {".wiz", "application/msword"},
                {".wk1", "application/x-123"},
                {".wks", "application/vnd.ms-works"},
                {".wlmp", "application/wlmoviemaker"},
                {".wlpginstall", "application/x-wlpg-detect"},
                {".wlpginstall3", "application/x-wlpg3-detect"},
                {".wm", "video/x-ms-wm"},
                {".wma", "audio/x-ms-wma"},
                {".wmd", "application/x-ms-wmd"},
                {".wmf", "windows/metafile"},
                {".wml", "text/vnd.wap.wml"},
                {".wmlc", "application/vnd.wap.wmlc"},
                {".wmls", "text/vnd.wap.wmlscript"},
                {".wmlsc", "application/vnd.wap.wmlscriptc"},
                {".wmp", "video/x-ms-wmp"},
                {".wmv", "video/x-ms-wmv"},
                {".wmx", "video/x-ms-wmx"},
                {".wmz", "application/x-ms-wmz"},
                {".woff", "application/font-woff"},
                {".woff2", "application/font-woff2"},
                {".word", "application/msword"},
                {".wp", "application/wordperfect"},
                {".wp5", "application/wordperfect"},
                {".wp6", "application/wordperfect"},
                {".wpd", "application/wordperfect"},
                {".wpl", "application/vnd.ms-wpl"},
                {".wps", "application/vnd.ms-works"},
                {".wq1", "application/x-lotus"},
                {".wri", "application/mswrite"},
                {".wrl", "application/x-world"},
                {".wrz", "x-world/x-vrml"},
                {".wsc", "text/scriplet"},
                {".wsdl", "text/xml"},
                {".wsrc", "application/x-wais-source"},
                {".wtk", "application/x-wintalk"},
                {".wvx", "video/x-ms-wvx"},

                {".x", "application/directx"},
                {".x-png", "image/png"},
                {".xaf", "x-world/x-vrml"},
                {".xaml", "application/xaml+xml"},
                {".xap", "application/x-silverlight-app"},
                {".xbap", "application/x-ms-xbap"},
                {".xbm", "image/x-xbitmap"},
                {".xdr", "video/x-amt-demorun"},
                {".xgz", "xgl/drawing"},
                {".xht", "application/xhtml+xml"},
                {".xhtml", "application/xhtml+xml"},
                {".xif", "image/vnd.xiff"},
                {".xl", "application/excel"},
                {".xla", "application/vnd.ms-excel"},
                {".xlam", "application/vnd.ms-excel.addin.macroEnabled.12"},
                {".xlb", "application/vnd.ms-excel"},
                {".xlc", "application/vnd.ms-excel"},
                {".xld", "application/vnd.ms-excel"},
                {".xlk", "application/vnd.ms-excel"},
                {".xll", "application/vnd.ms-excel"},
                {".xlm", "application/vnd.ms-excel"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
                {".xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12"},
                {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                {".xlt", "application/vnd.ms-excel"},
                {".xltm", "application/vnd.ms-excel.template.macroEnabled.12"},
                {".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
                {".xlv", "application/vnd.ms-excel"},
                {".xlw", "application/vnd.ms-excel"},
                {".xm", "audio/xm"},
                {".xml", "application/xml"},
                {".xmp", "application/octet-stream"},
                {".xmta", "application/xml"},
                {".xmz", "xgl/movie"},
                {".xof", "x-world/x-vrml"},
                {".xoml", "text/plain"},
                {".xpix", "application/x-vnd.ls-xpix"},
                {".xpm", "image/x-xpixmap"},
                {".xps", "application/vnd.ms-xpsdocument"},
                {".xrm-ms", "text/xml"},
                {".xsc", "application/xml"},
                {".xsd", "text/xml"},
                {".xsf", "text/xml"},
                {".xsl", "text/xml"},
                {".xslt", "text/xml"},
                {".xsn", "application/octet-stream"},
                {".xspf", "application/xspf+xml"},
                {".xsr", "video/x-amt-showrun"},
                {".xss", "application/xml"},
                {".xtp", "application/octet-stream"},
                {".xwd", "image/x-xwd"},
                {".xyz", "chemical/x-pdb"},

                {".z", "application/x-compress"},                
                {".zip", "application/zip"},
                {".zoo", "application/octet-stream"},
                {".zsh", "text/x-script.zsh"},


                {"application/fsharp-script", ".fsx"},
                {"application/msaccess", ".adp"},
                {"application/msword", ".doc"},
                {"application/octet-stream", ".bin"},
                {"application/onenote", ".one"},
                {"application/postscript", ".eps"},
                {"application/step", ".step"},
                {"application/vnd.ms-excel", ".xls"},
                {"application/vnd.ms-powerpoint", ".ppt"},
                {"application/vnd.ms-works", ".wks"},
                {"application/vnd.visio", ".vsd"},
                {"application/x-director", ".dir"},
                {"application/x-msdos-program", ".exe"},
                {"application/x-shockwave-flash", ".swf"},
                {"application/x-x509-ca-cert", ".cer"},
                {"application/x-zip-compressed", ".zip"},
                {"application/xhtml+xml", ".xhtml"},
                {"application/xml", ".xml"}, // anomaly, .xml -> text/xml, but application/xml -> many things, but all are xml, so safest is .xml
                {"audio/aac", ".AAC"},
                {"audio/aiff", ".aiff"},
                {"audio/basic", ".snd"},
                {"audio/mid", ".midi"},
                {"audio/mp4", ".m4a"}, // one way mapping only, mime -> ext
                {"audio/wav", ".wav"},
                {"audio/x-m4a", ".m4a"},
                {"audio/x-mpegurl", ".m3u"},
                {"audio/x-pn-realaudio", ".ra"},
                {"audio/x-smd", ".smd"},
                {"image/bmp", ".bmp"},
                {"image/jpeg", ".jpg"},
                {"image/pict", ".pic"},
                {"image/png", ".png"}, // Defined in [RFC-2045], [RFC-2048]
                {"image/x-png", ".png"}, // See https://www.w3.org/TR/PNG/#A-Media-type :"It is recommended that implementations also recognize the media type "image/x-png"."
                {"image/tiff", ".tiff"},
                {"image/x-macpaint", ".mac"},
                {"image/x-quicktime", ".qti"},
                {"message/rfc822", ".eml"},
                {"text/calendar", ".ics"},
                {"text/html", ".html"},
                {"text/plain", ".txt"},
                {"text/scriptlet", ".wsc"},
                {"text/xml", ".xml"},
                {"video/3gpp", ".3gp"},
                {"video/3gpp2", ".3gp2"},
                {"video/mp4", ".mp4"},
                {"video/mpeg", ".mpg"},
                {"video/quicktime", ".mov"},
                {"video/vnd.dlna.mpeg-tts", ".m2t"},
                {"video/x-dv", ".dv"},
                {"video/x-la-asf", ".lsf"},
                {"video/x-ms-asf", ".asf"},
                {"x-world/x-vrml", ".xof"},

                };
        #endregion
        private static IDictionary<string, string> BuildList()
        {
            var mappings = base_mime_mappings_list; // Set the base list

            // Add the mimetype to the list so a reverse lookup can be performed 
            foreach (var mapping in base_mime_mappings_list.ToList())
            {
                if (!mappings.ContainsKey(mapping.Value))
                {
                    mappings.Add(mapping.Value, mapping.Key);
                }
            }

            return mappings;

        }
        /// <summary>Return the Mime type for a supplied FileExtension</summary>
        /// <param name="FileExt">The file extension (can include .)</param>
        /// <param name="throwErrorIfNotFound">Cause a throw to happen if the File Extension is not found</param>
        /// <returns>A string containing the MimeType</returns>
        public static string GetMimeType(string FileExt, bool throwErrorIfNotFound = true)
        {           
            if (FileExt == null)
            {
                throw new ArgumentNullException("No file extension provided");
            }

            if (!FileExt.StartsWith(".") && FileExt.Length > 1)
            {
                FileExt = $".{FileExt}";
            }

            if (_mappings.Value.TryGetValue(FileExt, out string mimeType))
            {
                return mimeType;
            }

            if (throwErrorIfNotFound)
            {
                throw new ArgumentException("Requested File Extension is not registered: " + FileExt);
            }

            return string.Empty;
        }
        /// <summary>Return the file extension from a given mime type string</summary>
        /// <param name="mimeType">The Mime Type to find</param>
        /// <param name="throwErrorIfNotFound">Cause a throw to happen if the Mime type is not found</param>
        /// <returns>String containing the extension</returns>
        /// <remarks>This will not be perfect , if any extension has the same MimeType the returned extension may be wrong.</remarks>
        public static string GetExtension(string mimeType, bool throwErrorIfNotFound = true)
        {
            if (mimeType == null)
            {
                throw new ArgumentNullException(nameof(mimeType));
            }

            if (mimeType.StartsWith("."))
            {
                throw new ArgumentException("Requested mime type is not valid: " + mimeType);
            }

            if (_mappings.Value.TryGetValue(mimeType, out string extension))
            {
                return extension;
            }

            if (throwErrorIfNotFound)
            {
                throw new ArgumentException("Requested mime type is not registered: " + mimeType);
            }

            return string.Empty;
        }
    }
}
